import type { TenantInvitationItem, TenantUserItem } from "../types/tenant-users"

export interface TenantUserSeed {
  users: TenantUserItem[]
  invitations: TenantInvitationItem[]
}

export const TENANT_USER_SEEDS: Record<string, TenantUserSeed> = {
  "1": {
    users: [
      {
        id: "user-1",
        displayName: "Admin User",
        email: "admin@infera.ai",
        role: "Admin",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-01T00:00:00Z",
      },
      {
        id: "user-2",
        displayName: "Member One",
        email: "member1@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-02T00:00:00Z",
      },
      {
        id: "user-3",
        displayName: "Finance user",
        email: "finance@infera.ai",
        role: "Finance",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-03T00:00:00Z",
      },
      {
        id: "user-4",
        displayName: "Disabled User",
        email: "disabled@infera.ai",
        role: "Member",
        status: "Disabled",
        lastLoginAt: null,
        createdAt: "2024-01-04T00:00:00Z",
      },
      {
        id: "user-5",
        displayName: "Alice Chen",
        email: "alice.chen@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-05T00:00:00Z",
      },
      {
        id: "user-6",
        displayName: "Bob Li",
        email: "bob.li@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-06T00:00:00Z",
      },
      {
        id: "user-7",
        displayName: "Cindy Zhao",
        email: "cindy.zhao@infera.ai",
        role: "Finance",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-07T00:00:00Z",
      },
      {
        id: "user-8",
        displayName: "David Wang",
        email: "david.wang@infera.ai",
        role: "Member",
        status: "Disabled",
        lastLoginAt: null,
        createdAt: "2024-01-08T00:00:00Z",
      },
      {
        id: "user-9",
        displayName: "Ethan Sun",
        email: "ethan.sun@infera.ai",
        role: "Admin",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-09T00:00:00Z",
      },
      {
        id: "user-10",
        displayName: "Fiona Guo",
        email: "fiona.guo@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-10T00:00:00Z",
      },
      {
        id: "user-11",
        displayName: "Grace Xu",
        email: "grace.xu@infera.ai",
        role: "Finance",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-11T00:00:00Z",
      },
      {
        id: "user-12",
        displayName: "Henry Ma",
        email: "henry.ma@infera.ai",
        role: "Member",
        status: "Disabled",
        lastLoginAt: null,
        createdAt: "2024-01-12T00:00:00Z",
      },
      {
        id: "user-13",
        displayName: "Iris Lin",
        email: "iris.lin@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-13T00:00:00Z",
      },
      {
        id: "user-14",
        displayName: "Jack He",
        email: "jack.he@infera.ai",
        role: "Finance",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-14T00:00:00Z",
      },
      {
        id: "user-15",
        displayName: "Kelly Zhou",
        email: "kelly.zhou@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-15T00:00:00Z",
      },
      {
        id: "user-16",
        displayName: "Leo Peng",
        email: "leo.peng@infera.ai",
        role: "Admin",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-16T00:00:00Z",
      },
      {
        id: "user-17",
        displayName: "Mia Liu",
        email: "mia.liu@infera.ai",
        role: "Member",
        status: "Disabled",
        lastLoginAt: null,
        createdAt: "2024-01-17T00:00:00Z",
      },
      {
        id: "user-18",
        displayName: "Nathan Yu",
        email: "nathan.yu@infera.ai",
        role: "Finance",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-18T00:00:00Z",
      },
      {
        id: "user-19",
        displayName: "Olivia Qian",
        email: "olivia.qian@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-19T00:00:00Z",
      },
      {
        id: "user-20",
        displayName: "Peter Ren",
        email: "peter.ren@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-20T00:00:00Z",
      },
      {
        id: "user-21",
        displayName: "Queenie Song",
        email: "queenie.song@infera.ai",
        role: "Finance",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-21T00:00:00Z",
      },
      {
        id: "user-22",
        displayName: "Ryan Tan",
        email: "ryan.tan@infera.ai",
        role: "Member",
        status: "Disabled",
        lastLoginAt: null,
        createdAt: "2024-01-22T00:00:00Z",
      },
      {
        id: "user-23",
        displayName: "Sophia Gao",
        email: "sophia.gao@infera.ai",
        role: "Admin",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-23T00:00:00Z",
      },
      {
        id: "user-24",
        displayName: "Tony Deng",
        email: "tony.deng@infera.ai",
        role: "Member",
        status: "Active",
        lastLoginAt: new Date().toISOString(),
        createdAt: "2024-01-24T00:00:00Z",
      },
    ],
    invitations: [
      {
        id: "inv-1",
        email: "invitee1@example.com",
        role: "Member",
        status: "Pending",
        createdAt: new Date().toISOString(),
      },
      {
        id: "inv-2",
        email: "invitee2@example.com",
        role: "Finance",
        status: "Pending",
        createdAt: new Date().toISOString(),
      },
    ],
  },
}
