/**
 * Design Token System - Theme Presets
 * Pre-configured color schemes for light and dark modes
 */

import type { ThemePreset } from "@/types/theme"

export const themePresets: ThemePreset[] = [
	{
		key: "sky-blue",
		name: "天空蓝",
		description: "清新明亮的蓝色主题",
		schemes: {
			light: {
				brand: {
					primary: "#5d87ff",
					primaryHover: "#4570e6",
					primaryActive: "#3d5fcc",
					primaryBg: "#e8f0ff",
				},
				functional: {
					success: "#52c41a",
					successBg: "#f6ffed",
					warning: "#faad14",
					warningBg: "#fffbe6",
					error: "#f5222d",
					errorBg: "#fff1f0",
					info: "#1890ff",
					infoBg: "#e6f7ff",
				},
				text: {
					primary: "#1a1a1a",
					secondary: "#666666",
					tertiary: "#999999",
					inverse: "#ffffff",
					link: "#5d87ff",
					linkHover: "#4570e6",
				},
				background: {
					canvas: "#f5f7fa",
					container: "#ffffff",
					elevated: "#ffffff",
					layout: "#ffffff",
					hover: "#f5f7fa",
					active: "#e8f0ff",
				},
				border: {
					base: "#e0e0e0",
					strong: "#bdbdbd",
					subtle: "#f0f0f0",
				},
				shadow: {
					sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
					md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
					lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
				},
			},
			dark: {
				brand: {
					primary: "#6b93ff",
					primaryHover: "#8aabff",
					primaryActive: "#5d87ff",
					primaryBg: "#1a2744",
				},
				functional: {
					success: "#73d13d",
					successBg: "#162312",
					warning: "#ffc53d",
					warningBg: "#2b2111",
					error: "#ff4d4f",
					errorBg: "#2a1215",
					info: "#40a9ff",
					infoBg: "#111d2c",
				},
				text: {
					primary: "#e8e8e8",
					secondary: "#a0a0a0",
					tertiary: "#707070",
					inverse: "#1a1a1a",
					link: "#6b93ff",
					linkHover: "#8aabff",
				},
				background: {
					canvas: "#0a0a0a",
					container: "#1a1a1a",
					elevated: "#242424",
					layout: "#141414",
					hover: "#242424",
					active: "#1a2744",
				},
				border: {
					base: "#303030",
					strong: "#404040",
					subtle: "#1f1f1f",
				},
				shadow: {
					sm: "0 1px 2px 0 rgba(0, 0, 0, 0.3)",
					md: "0 4px 6px -1px rgba(0, 0, 0, 0.4)",
					lg: "0 10px 15px -3px rgba(0, 0, 0, 0.5)",
				},
			},
		},
	},
	{
		key: "geek-blue",
		name: "极客蓝",
		description: "专业深邃的蓝色主题",
		schemes: {
			light: {
				brand: {
					primary: "#1d4ed8",
					primaryHover: "#1e40af",
					primaryActive: "#1e3a8a",
					primaryBg: "#dbeafe",
				},
				functional: {
					success: "#10b981",
					successBg: "#d1fae5",
					warning: "#f59e0b",
					warningBg: "#fef3c7",
					error: "#ef4444",
					errorBg: "#fee2e2",
					info: "#3b82f6",
					infoBg: "#dbeafe",
				},
				text: {
					primary: "#111827",
					secondary: "#6b7280",
					tertiary: "#9ca3af",
					inverse: "#ffffff",
					link: "#1d4ed8",
					linkHover: "#1e40af",
				},
				background: {
					canvas: "#f9fafb",
					container: "#ffffff",
					elevated: "#ffffff",
					layout: "#ffffff",
					hover: "#f3f4f6",
					active: "#dbeafe",
				},
				border: {
					base: "#e5e7eb",
					strong: "#d1d5db",
					subtle: "#f3f4f6",
				},
			},
			dark: {
				brand: {
					primary: "#3b82f6",
					primaryHover: "#60a5fa",
					primaryActive: "#2563eb",
					primaryBg: "#1e3a8a",
				},
				functional: {
					success: "#34d399",
					successBg: "#064e3b",
					warning: "#fbbf24",
					warningBg: "#78350f",
					error: "#f87171",
					errorBg: "#7f1d1d",
					info: "#60a5fa",
					infoBg: "#1e3a8a",
				},
				text: {
					primary: "#f9fafb",
					secondary: "#d1d5db",
					tertiary: "#9ca3af",
					inverse: "#111827",
					link: "#60a5fa",
					linkHover: "#93c5fd",
				},
				background: {
					canvas: "#030712",
					container: "#111827",
					elevated: "#1f2937",
					layout: "#0f172a",
					hover: "#1f2937",
					active: "#1e3a8a",
				},
				border: {
					base: "#374151",
					strong: "#4b5563",
					subtle: "#1f2937",
				},
			},
		},
	},
	{
		key: "mint-green",
		name: "薄荷绿",
		description: "清新自然的绿色主题",
		schemes: {
			light: {
				brand: {
					primary: "#059669",
					primaryHover: "#047857",
					primaryActive: "#065f46",
					primaryBg: "#d1fae5",
				},
				functional: {
					success: "#10b981",
					successBg: "#d1fae5",
					warning: "#f59e0b",
					warningBg: "#fef3c7",
					error: "#ef4444",
					errorBg: "#fee2e2",
					info: "#06b6d4",
					infoBg: "#cffafe",
				},
				text: {
					primary: "#111827",
					secondary: "#6b7280",
					tertiary: "#9ca3af",
					inverse: "#ffffff",
					link: "#059669",
					linkHover: "#047857",
				},
				background: {
					canvas: "#f0fdf4",
					container: "#ffffff",
					elevated: "#ffffff",
					layout: "#ffffff",
					hover: "#f0fdf4",
					active: "#d1fae5",
				},
				border: {
					base: "#e5e7eb",
					strong: "#d1d5db",
					subtle: "#f3f4f6",
				},
			},
			dark: {
				brand: {
					primary: "#10b981",
					primaryHover: "#34d399",
					primaryActive: "#059669",
					primaryBg: "#064e3b",
				},
				functional: {
					success: "#34d399",
					successBg: "#064e3b",
					warning: "#fbbf24",
					warningBg: "#78350f",
					error: "#f87171",
					errorBg: "#7f1d1d",
					info: "#22d3ee",
					infoBg: "#164e63",
				},
				text: {
					primary: "#f9fafb",
					secondary: "#d1d5db",
					tertiary: "#9ca3af",
					inverse: "#111827",
					link: "#34d399",
					linkHover: "#6ee7b7",
				},
				background: {
					canvas: "#022c22",
					container: "#064e3b",
					elevated: "#065f46",
					layout: "#064e3b",
					hover: "#065f46",
					active: "#047857",
				},
				border: {
					base: "#047857",
					strong: "#059669",
					subtle: "#065f46",
				},
			},
		},
	},
	{
		key: "sunset-orange",
		name: "日落橙",
		description: "温暖活力的橙色主题",
		schemes: {
			light: {
				brand: {
					primary: "#ea580c",
					primaryHover: "#c2410c",
					primaryActive: "#9a3412",
					primaryBg: "#ffedd5",
				},
				functional: {
					success: "#10b981",
					successBg: "#d1fae5",
					warning: "#f59e0b",
					warningBg: "#fef3c7",
					error: "#ef4444",
					errorBg: "#fee2e2",
					info: "#3b82f6",
					infoBg: "#dbeafe",
				},
				text: {
					primary: "#111827",
					secondary: "#6b7280",
					tertiary: "#9ca3af",
					inverse: "#ffffff",
					link: "#ea580c",
					linkHover: "#c2410c",
				},
				background: {
					canvas: "#fff7ed",
					container: "#ffffff",
					elevated: "#ffffff",
					layout: "#ffffff",
					hover: "#fff7ed",
					active: "#ffedd5",
				},
				border: {
					base: "#e5e7eb",
					strong: "#d1d5db",
					subtle: "#f3f4f6",
				},
			},
			dark: {
				brand: {
					primary: "#fb923c",
					primaryHover: "#fdba74",
					primaryActive: "#f97316",
					primaryBg: "#7c2d12",
				},
				functional: {
					success: "#34d399",
					successBg: "#064e3b",
					warning: "#fbbf24",
					warningBg: "#78350f",
					error: "#f87171",
					errorBg: "#7f1d1d",
					info: "#60a5fa",
					infoBg: "#1e3a8a",
				},
				text: {
					primary: "#f9fafb",
					secondary: "#d1d5db",
					tertiary: "#9ca3af",
					inverse: "#111827",
					link: "#fb923c",
					linkHover: "#fdba74",
				},
				background: {
					canvas: "#431407",
					container: "#7c2d12",
					elevated: "#9a3412",
					layout: "#7c2d12",
					hover: "#9a3412",
					active: "#c2410c",
				},
				border: {
					base: "#9a3412",
					strong: "#c2410c",
					subtle: "#7c2d12",
				},
			},
		},
	},
]

export const defaultThemeSettings = {
	mode: "system" as const,
	activePreset: "sky-blue",
	fontFamily: "inter",
	layout: {
		menuLayout: "single" as const,
		containerWidth: "fixed" as const,
		sidebarWidth: 240,
		sidebarCollapsedWidth: 64,
		headerHeight: 64,
	},
	ui: {
		showBreadcrumb: true,
		showBreadcrumbIcon: true,
		pageAnimation: "slide-left" as const,
		borderRadius: 12,
	},
}
