/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BlankRouteRouteImport } from './routes/_blank/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as Errors500RouteImport } from './routes/errors/500'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as Errors403RouteImport } from './routes/errors/403'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/_dashboard/index'
import { Route as BlankAuthLoginRouteImport } from './routes/_blank/_auth/login'
import { Route as AuthenticatedCoreUsersRouteImport } from './routes/_authenticated/_core/users'
import { Route as AuthenticatedCoreProfileRouteImport } from './routes/_authenticated/_core/profile'

const BlankRouteRoute = BlankRouteRouteImport.update({
  id: '/_blank',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/_dashboard/',
    path: '/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlankAuthLoginRoute = BlankAuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => BlankRouteRoute,
} as any)
const AuthenticatedCoreUsersRoute = AuthenticatedCoreUsersRouteImport.update({
  id: '/_core/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoreProfileRoute =
  AuthenticatedCoreProfileRouteImport.update({
    id: '/_core/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/profile': typeof AuthenticatedCoreProfileRoute
  '/users': typeof AuthenticatedCoreUsersRoute
  '/login': typeof BlankAuthLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedDashboardIndexRoute
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/profile': typeof AuthenticatedCoreProfileRoute
  '/users': typeof AuthenticatedCoreUsersRoute
  '/login': typeof BlankAuthLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_blank': typeof BlankRouteRouteWithChildren
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/_authenticated/_core/profile': typeof AuthenticatedCoreProfileRoute
  '/_authenticated/_core/users': typeof AuthenticatedCoreUsersRoute
  '/_blank/_auth/login': typeof BlankAuthLoginRoute
  '/_authenticated/_dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/profile'
    | '/users'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/profile'
    | '/users'
    | '/login'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_blank'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/_authenticated/_core/profile'
    | '/_authenticated/_core/users'
    | '/_blank/_auth/login'
    | '/_authenticated/_dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BlankRouteRoute: typeof BlankRouteRouteWithChildren
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_blank': {
      id: '/_blank'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BlankRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_dashboard/': {
      id: '/_authenticated/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_blank/_auth/login': {
      id: '/_blank/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof BlankAuthLoginRouteImport
      parentRoute: typeof BlankRouteRoute
    }
    '/_authenticated/_core/users': {
      id: '/_authenticated/_core/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedCoreUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_core/profile': {
      id: '/_authenticated/_core/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedCoreProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCoreProfileRoute: typeof AuthenticatedCoreProfileRoute
  AuthenticatedCoreUsersRoute: typeof AuthenticatedCoreUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCoreProfileRoute: AuthenticatedCoreProfileRoute,
  AuthenticatedCoreUsersRoute: AuthenticatedCoreUsersRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlankRouteRouteChildren {
  BlankAuthLoginRoute: typeof BlankAuthLoginRoute
}

const BlankRouteRouteChildren: BlankRouteRouteChildren = {
  BlankAuthLoginRoute: BlankAuthLoginRoute,
}

const BlankRouteRouteWithChildren = BlankRouteRoute._addFileChildren(
  BlankRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BlankRouteRoute: BlankRouteRouteWithChildren,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
